language: node_js
node_js: '4.0'
deploy:
  provider: heroku
  api_key:
    secure: I39fzr0m2HzEqWynqphkeBhwbxur9jMl9CbOX9bw2R+YofG3YLWJ9wybZkPPpp/5pWYzfrM7lckFmyfnn/a67d2sKaYCrl4y9Xl/UjV7uTsGHVcsCfFIOMWnYoB+WCZsTWWDRANZPnBCKUmgQZ6VxahEC7BA2iNL1alDkXw1K1NMZ2zasQUkjhQG/BsLaBREvpZX85xDtAfYNfSapjOfFcm7BC8K6mJfrFQP9wD+sDUYy7McRqUbyDGPDYensczMcpJYnQ8WgPSY0c09VQK+ABNr4TCPGt7JIKdzPLJkZ93nzqHVRLlFEaTsm73FD95W+qS64TQ8QI+h8O8bZFx5BwxwZYLEbAhYVbVeVrJJF8YZpUOlWWVNm40h8h8eTODvtY0ZooeUd5duqCcMpiO8nyWXMg5vhCitFW+aL8LyiNw2p4WlkClwT0rsACMdy14KzS9IsKTfueRvL2vN39TJziF9H4i3MFhljG9gXoElr+Q68RJJvLO/7VTwaLAG4rQZIFXptA9EFlIrMGJ59iJy6vRDW2JebOMZZMIztjBi8C0y2S7beaLS16WD1Bk0Fq9Bo9gH72AQ3CfPGXZVJ5Mnm6+pkOhZTAHc4+1DggUwpEdNf8tAQrsdl3nBR8b8qdCLLkL8JwFNbN63hdh18/lz/DadNvW3awii0O8Sw0gmduk=
  app: tickets-by-node
  on:
    repo: NiceDay-Group/tickets-by-node
notifications:
  slack:
    secure: F55aj4rgg1PsUr/AWO2seD7iSZ5cxwA3x6XehF8bp4KSsfh/9SlVCWcjRp3whkRL4Ul722WvEd1cZuulHZO4LqSJ3OqiujEAxRRDiVJrShS858OPUWgivHULQ3xGw0mh4vCCpcFfP1RDqX/MtmVshe5wkpUKg7Wm4ITofFNpj3wFaNC7/+3n8qfi2mv5p6eUQhcRKFRsd6fUMtLC1HbmkGgEv2lmZPFke76UF1YxyDrEESZsYYHCfsJioKKCKRnnsDFEPQ/sQpA2EgoB5Nu7cR41VGZHzbuLcnaaToGuKTseLEswhGov+ZUjWhGH6XWnAovV2jumWRlr619KNJLlT3V2kv9MrDypSZZneLNAp4N0Ki0GEjhiBAy9FQ2EpB2vyIhuXQ15R89Ursz+XknlaZrQVgXDvG+8h2IfVdadWQZ51LDSefjiR93WlfJHMnluMjRAI4JBsxYOZp7gbvKUKR50LaKoEmgGA9ESgJSqCE+AsdzXN6EKP+SnyvDyCmgug0wqvIM5i5b6qSwo3N5VkA+Ylukn8aQFHa3Jx1+aiWaDCmHZNQTNLVtvGMepMmfyvbbHyu/6fG578ZNS/Z/MmQ8bBt+81x0n6yP2zSOeJlXBi76KmSSHJquDyYnnw4qyhW9dLecNq38Q4Q34982IypuA0+KSqajtVi7CqW68izw=
